Сетка страницы и крупных блоков на флексах для главной страницы
htmlacademy-htmlcss/1688167-device-32 pull request #5
Opened 2021-10-18 21:41 UTC by IvoLord

---
:mortar_board: [Сетка страницы и крупных блоков на флексах для главной страницы](https://up.htmlacademy.ru/htmlcss/32/user/1688167/tasks/7)

2021-10-19 18:30 UTC, andreysgra requested changes

2021-10-19 18:30 UTC, andreysgra commented on index.html
> +          </div>
Здесь стоит не `header` оборачивать `div.container`, а `div.container` положить внутрь `header`:
```
<header class="main-header">
  <div class="container">
    <!-- Весь контент шапки сайта -->
  </div>
</header>
```

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +  order: 1;
А не проще ли поменять в разметке местами `navigation-user` и `navigation-main`?

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +}
Соответственно и флекс здесь не понадобится. Весь этот "огород" с флексом ради только изменения порядка следования `navigation-user` и `navigation-main`.

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +  width: 1041px;
Не нужно ограничивать ширину этого блока. Правильнее задать паддинги слева и справа:
![image](https://user-images.githubusercontent.com/17790771/137967042-d63115c9-e594-4bf2-b73d-99fe2ff73de6.png)

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +}
Тоже самое и здесь.

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +}
Нужно добавить перенос строк в флекс контейнере  - `flex-wrap: wrap`, иначе, при добавлении, новые элементы будут уходить вправо:
![image](https://user-images.githubusercontent.com/17790771/137967756-3ff5445c-bb7e-48da-8717-0697710d4236.png)

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +}
`kategories` - как-то не по-английски. Правильно будет `categories`.

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +}
А к чему здесь `flex`? И без него всё хорошо.

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +}
Здесь `flex` не нужен.

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +  flex-direction: column;
Здесь `flex` не нужен.

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
> +}
В этом блоке нужно сделать пару дополнительных обёрток (а флекс выкинуть за ненадобностью), так как такое количество элементов с разной геометрией и с переносом на новую линию будет неустойчиво и сетка может легко сломаться. Добавьте такие обёртки:
![image](https://user-images.githubusercontent.com/17790771/137969266-ac783b4b-3dcc-4705-9055-da7b4449c27f.png)

2021-10-19 18:30 UTC, andreysgra commented on styles/styles.css
>  body {
Нужно обнулить дефолтные `margin` у `body`.

2021-10-20 10:19 UTC, IvoLord commented on styles/styles.css
> +}
=D спасибо, просто в другой стране, и вынужден перемешивать в голве 4 языка )

2021-10-21 14:36 UTC, merged